kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: demo-vol-claim-0
spec:
  storageClassName: csi-one-replica-autoplace-thin-lvm
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4G

