apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: "linstor-csi-thin-lvm-r1"
provisioner: linstor.csi.linbit.com
parameters:
  autoPlace: "1"
  storagePool: "thin-lvm"
reclaimPolicy: Delete
