apiVersion: storage.k8s.io/v1
kind: StorageClass
  annotations:
  storageclass.kubernetes.io/is-default-class: "true"
metadata:
  name: "csi-one-replica-autoplace-thin-lvm"
parameters:
  autoplace: "1"
  storagePool: "thin-lvm"
provisioner: io.drbd.linstor-csi
reclaimPolicy: Delete
