apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: "csi-one-replica-autoplace-thin-lvm"
provisioner: linstor.csi.linbit.com
parameters:
  autoPlace: "1"
  storagePool: "thin-lvm"
reclaimPolicy: Delete
