---
apiVersion: batch/v1
kind: Job
metadata:
  name: cassandra-loadgen
spec:
  template:
    metadata:
      name: cassandra-loadgen
      labels:
        app: cassandra-loadgen
    spec:
      restartPolicy: Never
      containers:
      - name: cassandra-loadgen
        image: cassandra
        command: ["/bin/bash"]
        args: ["-c", "cassandra-stress write duration=5m no-warmup -node cassandra-0.cassandra"]
        tty: true 

